### ISSUE TITLE
コンパイルエラー: 'FaceView' has no member 'changeScale'

### ISSUE THREAD

**Issue by sf-arte** [sf-arte/Stanford#2]
`FaceView`クラス内で`changeScale`を定義しているのにもかかわらずコンパイルが通らず．
クリーンビルドをしても解決せず．

**Comment by nkgwj** [comment]
セレクタのシンタックスをちゃんと確認していないのですが、

#selector(FaceView.changeScale(_:))

ではなくて

#selector(faceView.changeScale(_:))

でもダメでしょうか

**Comment by sf-arte** [comment]
`#selector(FaceView.changeScale(recognizer:))`で動きました．
ありがとうございました．
