### ISSUE TITLE
dispatch_async in Swift 3

### ISSUE THREAD

**Issue by sf-arte** [sf-arte/Stanford#3]
```
dispatch_async(dispatch_get_global_queue(QOS_CLASS_USER_INITIATED, 0))
```

の代わりに，

```
DispatchQueue.global(attributes: .qosUserInitiated).async
```

とする．

**Comment by nkgwj** [comment]
GCDは大幅に変わっていると思うので、必要に応じてAppleのWWDCの発表をご参照ください

https://developer.apple.com/videos/play/wwdc2016/720/

**Comment by sf-arte** [comment]
ありがとうございます．

**Comment by sf-arte** [comment]
[https://developer.apple.com/reference/dispatch/dispatchqueue](https://developer.apple.com/reference/dispatch/dispatchqueue)
リファレンスでは`global(qos: DispatchQoS.QoSClass)`となっているので最新のXcodeでは変更されている可能性あり．

```
dispatch_async(dispatch_get_main_queue())
```

は，

```
DispatchQueue.main.async
```

とする．
